import typing

from gi.repository import GObject
T = typing.TypeVar("T")

_namespace: str = "GL"
_version: str = "1.0"

def InitNames() -> None: ...

class bitfield(GObject.GPointer): ...

class boolean(GObject.GPointer): ...

class charARB(GObject.GPointer): ...

class clampf(GObject.GPointer): ...

class enum(GObject.GPointer): ...

class float(GObject.GPointer): ...

class handleARB(GObject.GPointer): ...

class int(GObject.GPointer): ...

class intptr(GObject.GPointer): ...

class sizei(GObject.GPointer): ...

class sizeiptr(GObject.GPointer): ...

class uint(GObject.GPointer): ...

class void(GObject.GPointer): ...

