import typing

from gi.repository import GObject
T = typing.TypeVar("T")

_namespace: str = "libxml2"
_version: str = "2.0"

def dummy() -> None: ...

class Char(GObject.GPointer): ...

class Doc(GObject.GPointer): ...

class DocPtr(GObject.GPointer): ...

class Node(GObject.GPointer): ...

class NodePtr(GObject.GPointer): ...

class NsPtr(GObject.GPointer): ...

class TextReader(GObject.GPointer): ...

class TextWriter(GObject.GPointer): ...

