import typing

from gi.repository import GObject
T = typing.TypeVar("T")

_namespace: str = "Vulkan"
_version: str = "1.0"

class AccelerationStructureCreateInfoNV(GObject.GPointer): ...

class AccelerationStructureInfoNV(GObject.GPointer): ...

class AccelerationStructureMemoryRequirementsInfoNV(GObject.GPointer): ...

class AccelerationStructureMemoryRequirementsTypeNV(GObject.GPointer): ...

class AccelerationStructureNV(GObject.GPointer): ...

class AccelerationStructureTypeNV(GObject.GPointer): ...

class AccessFlagBits(GObject.GPointer): ...

class AccessFlags(GObject.GPointer): ...

class AcquireNextImageInfoKHR(GObject.GPointer): ...

class AllocationCallbacks(GObject.GPointer): ...

class ApplicationInfo(GObject.GPointer): ...

class AttachmentDescription(GObject.GPointer): ...

class AttachmentDescription2KHR(GObject.GPointer): ...

class AttachmentDescriptionFlagBits(GObject.GPointer): ...

class AttachmentDescriptionFlags(GObject.GPointer): ...

class AttachmentLoadOp(GObject.GPointer): ...

class AttachmentReference(GObject.GPointer): ...

class AttachmentReference2KHR(GObject.GPointer): ...

class AttachmentSampleLocationsEXT(GObject.GPointer): ...

class AttachmentStoreOp(GObject.GPointer): ...

class BaseInStructure(GObject.GPointer): ...

class BaseOutStructure(GObject.GPointer): ...

class BindAccelerationStructureMemoryInfoNV(GObject.GPointer): ...

class BindBufferMemoryDeviceGroupInfo(GObject.GPointer): ...

class BindBufferMemoryDeviceGroupInfoKHR(GObject.GPointer): ...

class BindBufferMemoryInfo(GObject.GPointer): ...

class BindBufferMemoryInfoKHR(GObject.GPointer): ...

class BindImageMemoryDeviceGroupInfo(GObject.GPointer): ...

class BindImageMemoryDeviceGroupInfoKHR(GObject.GPointer): ...

class BindImageMemoryInfo(GObject.GPointer): ...

class BindImageMemoryInfoKHR(GObject.GPointer): ...

class BindImageMemorySwapchainInfoKHR(GObject.GPointer): ...

class BindImagePlaneMemoryInfo(GObject.GPointer): ...

class BindImagePlaneMemoryInfoKHR(GObject.GPointer): ...

class BindSparseInfo(GObject.GPointer): ...

class BlendFactor(GObject.GPointer): ...

class BlendOp(GObject.GPointer): ...

class BlendOverlapEXT(GObject.GPointer): ...

class Bool32(GObject.GPointer): ...

class BorderColor(GObject.GPointer): ...

class Buffer(GObject.GPointer): ...

class BufferCopy(GObject.GPointer): ...

class BufferCreateFlagBits(GObject.GPointer): ...

class BufferCreateFlags(GObject.GPointer): ...

class BufferCreateInfo(GObject.GPointer): ...

class BufferDeviceAddressCreateInfoEXT(GObject.GPointer): ...

class BufferDeviceAddressInfoEXT(GObject.GPointer): ...

class BufferImageCopy(GObject.GPointer): ...

class BufferMemoryBarrier(GObject.GPointer): ...

class BufferMemoryRequirementsInfo2(GObject.GPointer): ...

class BufferMemoryRequirementsInfo2KHR(GObject.GPointer): ...

class BufferUsageFlagBits(GObject.GPointer): ...

class BufferUsageFlags(GObject.GPointer): ...

class BufferView(GObject.GPointer): ...

class BufferViewCreateFlags(GObject.GPointer): ...

class BufferViewCreateInfo(GObject.GPointer): ...

class BuildAccelerationStructureFlagBitsNV(GObject.GPointer): ...

class BuildAccelerationStructureFlagsNV(GObject.GPointer): ...

class CalibratedTimestampInfoEXT(GObject.GPointer): ...

class CheckpointDataNV(GObject.GPointer): ...

class ChromaLocation(GObject.GPointer): ...

class ChromaLocationKHR(GObject.GPointer): ...

class ClearAttachment(GObject.GPointer): ...

class ClearColorValue(GObject.GPointer): ...

class ClearDepthStencilValue(GObject.GPointer): ...

class ClearRect(GObject.GPointer): ...

class ClearValue(GObject.GPointer): ...

class CmdProcessCommandsInfoNVX(GObject.GPointer): ...

class CmdReserveSpaceForCommandsInfoNVX(GObject.GPointer): ...

class CoarseSampleLocationNV(GObject.GPointer): ...

class CoarseSampleOrderCustomNV(GObject.GPointer): ...

class CoarseSampleOrderTypeNV(GObject.GPointer): ...

class ColorComponentFlagBits(GObject.GPointer): ...

class ColorComponentFlags(GObject.GPointer): ...

class ColorSpaceKHR(GObject.GPointer): ...

class CommandBuffer(GObject.GPointer): ...

class CommandBufferAllocateInfo(GObject.GPointer): ...

class CommandBufferBeginInfo(GObject.GPointer): ...

class CommandBufferInheritanceConditionalRenderingInfoEXT(GObject.GPointer): ...

class CommandBufferInheritanceInfo(GObject.GPointer): ...

class CommandBufferLevel(GObject.GPointer): ...

class CommandBufferResetFlagBits(GObject.GPointer): ...

class CommandBufferResetFlags(GObject.GPointer): ...

class CommandBufferUsageFlagBits(GObject.GPointer): ...

class CommandBufferUsageFlags(GObject.GPointer): ...

class CommandPool(GObject.GPointer): ...

class CommandPoolCreateFlagBits(GObject.GPointer): ...

class CommandPoolCreateFlags(GObject.GPointer): ...

class CommandPoolCreateInfo(GObject.GPointer): ...

class CommandPoolResetFlagBits(GObject.GPointer): ...

class CommandPoolResetFlags(GObject.GPointer): ...

class CommandPoolTrimFlags(GObject.GPointer): ...

class CommandPoolTrimFlagsKHR(GObject.GPointer): ...

class CompareOp(GObject.GPointer): ...

class ComponentMapping(GObject.GPointer): ...

class ComponentSwizzle(GObject.GPointer): ...

class ComponentTypeNV(GObject.GPointer): ...

class CompositeAlphaFlagBitsKHR(GObject.GPointer): ...

class CompositeAlphaFlagsKHR(GObject.GPointer): ...

class ComputePipelineCreateInfo(GObject.GPointer): ...

class ConditionalRenderingBeginInfoEXT(GObject.GPointer): ...

class ConditionalRenderingFlagBitsEXT(GObject.GPointer): ...

class ConditionalRenderingFlagsEXT(GObject.GPointer): ...

class ConformanceVersionKHR(GObject.GPointer): ...

class ConservativeRasterizationModeEXT(GObject.GPointer): ...

class CooperativeMatrixPropertiesNV(GObject.GPointer): ...

class CopyAccelerationStructureModeNV(GObject.GPointer): ...

class CopyDescriptorSet(GObject.GPointer): ...

class CoverageModulationModeNV(GObject.GPointer): ...

class CoverageReductionModeNV(GObject.GPointer): ...

class CullModeFlagBits(GObject.GPointer): ...

class CullModeFlags(GObject.GPointer): ...

class DebugMarkerMarkerInfoEXT(GObject.GPointer): ...

class DebugMarkerObjectNameInfoEXT(GObject.GPointer): ...

class DebugMarkerObjectTagInfoEXT(GObject.GPointer): ...

class DebugReportCallbackCreateInfoEXT(GObject.GPointer): ...

class DebugReportCallbackEXT(GObject.GPointer): ...

class DebugReportFlagBitsEXT(GObject.GPointer): ...

class DebugReportFlagsEXT(GObject.GPointer): ...

class DebugReportObjectTypeEXT(GObject.GPointer): ...

class DebugUtilsLabelEXT(GObject.GPointer): ...

class DebugUtilsMessageSeverityFlagBitsEXT(GObject.GPointer): ...

class DebugUtilsMessageSeverityFlagsEXT(GObject.GPointer): ...

class DebugUtilsMessageTypeFlagBitsEXT(GObject.GPointer): ...

class DebugUtilsMessageTypeFlagsEXT(GObject.GPointer): ...

class DebugUtilsMessengerCallbackDataEXT(GObject.GPointer): ...

class DebugUtilsMessengerCallbackDataFlagsEXT(GObject.GPointer): ...

class DebugUtilsMessengerCreateFlagsEXT(GObject.GPointer): ...

class DebugUtilsMessengerCreateInfoEXT(GObject.GPointer): ...

class DebugUtilsMessengerEXT(GObject.GPointer): ...

class DebugUtilsObjectNameInfoEXT(GObject.GPointer): ...

class DebugUtilsObjectTagInfoEXT(GObject.GPointer): ...

class DedicatedAllocationBufferCreateInfoNV(GObject.GPointer): ...

class DedicatedAllocationImageCreateInfoNV(GObject.GPointer): ...

class DedicatedAllocationMemoryAllocateInfoNV(GObject.GPointer): ...

class DependencyFlagBits(GObject.GPointer): ...

class DependencyFlags(GObject.GPointer): ...

class DescriptorBindingFlagBitsEXT(GObject.GPointer): ...

class DescriptorBindingFlagsEXT(GObject.GPointer): ...

class DescriptorBufferInfo(GObject.GPointer): ...

class DescriptorImageInfo(GObject.GPointer): ...

class DescriptorPool(GObject.GPointer): ...

class DescriptorPoolCreateFlagBits(GObject.GPointer): ...

class DescriptorPoolCreateFlags(GObject.GPointer): ...

class DescriptorPoolCreateInfo(GObject.GPointer): ...

class DescriptorPoolInlineUniformBlockCreateInfoEXT(GObject.GPointer): ...

class DescriptorPoolResetFlags(GObject.GPointer): ...

class DescriptorPoolSize(GObject.GPointer): ...

class DescriptorSet(GObject.GPointer): ...

class DescriptorSetAllocateInfo(GObject.GPointer): ...

class DescriptorSetLayout(GObject.GPointer): ...

class DescriptorSetLayoutBinding(GObject.GPointer): ...

class DescriptorSetLayoutBindingFlagsCreateInfoEXT(GObject.GPointer): ...

class DescriptorSetLayoutCreateFlagBits(GObject.GPointer): ...

class DescriptorSetLayoutCreateFlags(GObject.GPointer): ...

class DescriptorSetLayoutCreateInfo(GObject.GPointer): ...

class DescriptorSetLayoutSupport(GObject.GPointer): ...

class DescriptorSetLayoutSupportKHR(GObject.GPointer): ...

class DescriptorSetVariableDescriptorCountAllocateInfoEXT(GObject.GPointer): ...

class DescriptorSetVariableDescriptorCountLayoutSupportEXT(GObject.GPointer): ...

class DescriptorType(GObject.GPointer): ...

class DescriptorUpdateTemplate(GObject.GPointer): ...

class DescriptorUpdateTemplateCreateFlags(GObject.GPointer): ...

class DescriptorUpdateTemplateCreateFlagsKHR(GObject.GPointer): ...

class DescriptorUpdateTemplateCreateInfo(GObject.GPointer): ...

class DescriptorUpdateTemplateCreateInfoKHR(GObject.GPointer): ...

class DescriptorUpdateTemplateEntry(GObject.GPointer): ...

class DescriptorUpdateTemplateEntryKHR(GObject.GPointer): ...

class DescriptorUpdateTemplateKHR(GObject.GPointer): ...

class DescriptorUpdateTemplateType(GObject.GPointer): ...

class DescriptorUpdateTemplateTypeKHR(GObject.GPointer): ...

class Device(GObject.GPointer): ...

class DeviceAddress(GObject.GPointer): ...

class DeviceCreateFlags(GObject.GPointer): ...

class DeviceCreateInfo(GObject.GPointer): ...

class DeviceEventInfoEXT(GObject.GPointer): ...

class DeviceEventTypeEXT(GObject.GPointer): ...

class DeviceGeneratedCommandsFeaturesNVX(GObject.GPointer): ...

class DeviceGeneratedCommandsLimitsNVX(GObject.GPointer): ...

class DeviceGroupBindSparseInfo(GObject.GPointer): ...

class DeviceGroupBindSparseInfoKHR(GObject.GPointer): ...

class DeviceGroupCommandBufferBeginInfo(GObject.GPointer): ...

class DeviceGroupCommandBufferBeginInfoKHR(GObject.GPointer): ...

class DeviceGroupDeviceCreateInfo(GObject.GPointer): ...

class DeviceGroupDeviceCreateInfoKHR(GObject.GPointer): ...

class DeviceGroupPresentCapabilitiesKHR(GObject.GPointer): ...

class DeviceGroupPresentInfoKHR(GObject.GPointer): ...

class DeviceGroupPresentModeFlagBitsKHR(GObject.GPointer): ...

class DeviceGroupPresentModeFlagsKHR(GObject.GPointer): ...

class DeviceGroupRenderPassBeginInfo(GObject.GPointer): ...

class DeviceGroupRenderPassBeginInfoKHR(GObject.GPointer): ...

class DeviceGroupSubmitInfo(GObject.GPointer): ...

class DeviceGroupSubmitInfoKHR(GObject.GPointer): ...

class DeviceGroupSwapchainCreateInfoKHR(GObject.GPointer): ...

class DeviceMemory(GObject.GPointer): ...

class DeviceMemoryOverallocationCreateInfoAMD(GObject.GPointer): ...

class DeviceQueueCreateFlagBits(GObject.GPointer): ...

class DeviceQueueCreateFlags(GObject.GPointer): ...

class DeviceQueueCreateInfo(GObject.GPointer): ...

class DeviceQueueGlobalPriorityCreateInfoEXT(GObject.GPointer): ...

class DeviceQueueInfo2(GObject.GPointer): ...

class DeviceSize(GObject.GPointer): ...

class DiscardRectangleModeEXT(GObject.GPointer): ...

class DispatchIndirectCommand(GObject.GPointer): ...

class DisplayEventInfoEXT(GObject.GPointer): ...

class DisplayEventTypeEXT(GObject.GPointer): ...

class DisplayKHR(GObject.GPointer): ...

class DisplayModeCreateFlagsKHR(GObject.GPointer): ...

class DisplayModeCreateInfoKHR(GObject.GPointer): ...

class DisplayModeKHR(GObject.GPointer): ...

class DisplayModeParametersKHR(GObject.GPointer): ...

class DisplayModeProperties2KHR(GObject.GPointer): ...

class DisplayModePropertiesKHR(GObject.GPointer): ...

class DisplayNativeHdrSurfaceCapabilitiesAMD(GObject.GPointer): ...

class DisplayPlaneAlphaFlagBitsKHR(GObject.GPointer): ...

class DisplayPlaneAlphaFlagsKHR(GObject.GPointer): ...

class DisplayPlaneCapabilities2KHR(GObject.GPointer): ...

class DisplayPlaneCapabilitiesKHR(GObject.GPointer): ...

class DisplayPlaneInfo2KHR(GObject.GPointer): ...

class DisplayPlaneProperties2KHR(GObject.GPointer): ...

class DisplayPlanePropertiesKHR(GObject.GPointer): ...

class DisplayPowerInfoEXT(GObject.GPointer): ...

class DisplayPowerStateEXT(GObject.GPointer): ...

class DisplayPresentInfoKHR(GObject.GPointer): ...

class DisplayProperties2KHR(GObject.GPointer): ...

class DisplayPropertiesKHR(GObject.GPointer): ...

class DisplaySurfaceCreateFlagsKHR(GObject.GPointer): ...

class DisplaySurfaceCreateInfoKHR(GObject.GPointer): ...

class DrawIndexedIndirectCommand(GObject.GPointer): ...

class DrawIndirectCommand(GObject.GPointer): ...

class DrawMeshTasksIndirectCommandNV(GObject.GPointer): ...

class DriverIdKHR(GObject.GPointer): ...

class DrmFormatModifierPropertiesEXT(GObject.GPointer): ...

class DrmFormatModifierPropertiesListEXT(GObject.GPointer): ...

class DynamicState(GObject.GPointer): ...

class Event(GObject.GPointer): ...

class EventCreateFlags(GObject.GPointer): ...

class EventCreateInfo(GObject.GPointer): ...

class ExportFenceCreateInfo(GObject.GPointer): ...

class ExportFenceCreateInfoKHR(GObject.GPointer): ...

class ExportMemoryAllocateInfo(GObject.GPointer): ...

class ExportMemoryAllocateInfoKHR(GObject.GPointer): ...

class ExportMemoryAllocateInfoNV(GObject.GPointer): ...

class ExportSemaphoreCreateInfo(GObject.GPointer): ...

class ExportSemaphoreCreateInfoKHR(GObject.GPointer): ...

class ExtensionProperties(GObject.GPointer): ...

class Extent2D(GObject.GPointer): ...

class Extent3D(GObject.GPointer): ...

class ExternalBufferProperties(GObject.GPointer): ...

class ExternalBufferPropertiesKHR(GObject.GPointer): ...

class ExternalFenceFeatureFlagBits(GObject.GPointer): ...

class ExternalFenceFeatureFlagBitsKHR(GObject.GPointer): ...

class ExternalFenceFeatureFlags(GObject.GPointer): ...

class ExternalFenceFeatureFlagsKHR(GObject.GPointer): ...

class ExternalFenceHandleTypeFlagBits(GObject.GPointer): ...

class ExternalFenceHandleTypeFlagBitsKHR(GObject.GPointer): ...

class ExternalFenceHandleTypeFlags(GObject.GPointer): ...

class ExternalFenceHandleTypeFlagsKHR(GObject.GPointer): ...

class ExternalFenceProperties(GObject.GPointer): ...

class ExternalFencePropertiesKHR(GObject.GPointer): ...

class ExternalImageFormatProperties(GObject.GPointer): ...

class ExternalImageFormatPropertiesKHR(GObject.GPointer): ...

class ExternalImageFormatPropertiesNV(GObject.GPointer): ...

class ExternalMemoryBufferCreateInfo(GObject.GPointer): ...

class ExternalMemoryBufferCreateInfoKHR(GObject.GPointer): ...

class ExternalMemoryFeatureFlagBits(GObject.GPointer): ...

class ExternalMemoryFeatureFlagBitsKHR(GObject.GPointer): ...

class ExternalMemoryFeatureFlagBitsNV(GObject.GPointer): ...

class ExternalMemoryFeatureFlags(GObject.GPointer): ...

class ExternalMemoryFeatureFlagsKHR(GObject.GPointer): ...

class ExternalMemoryFeatureFlagsNV(GObject.GPointer): ...

class ExternalMemoryHandleTypeFlagBits(GObject.GPointer): ...

class ExternalMemoryHandleTypeFlagBitsKHR(GObject.GPointer): ...

class ExternalMemoryHandleTypeFlagBitsNV(GObject.GPointer): ...

class ExternalMemoryHandleTypeFlags(GObject.GPointer): ...

class ExternalMemoryHandleTypeFlagsKHR(GObject.GPointer): ...

class ExternalMemoryHandleTypeFlagsNV(GObject.GPointer): ...

class ExternalMemoryImageCreateInfo(GObject.GPointer): ...

class ExternalMemoryImageCreateInfoKHR(GObject.GPointer): ...

class ExternalMemoryImageCreateInfoNV(GObject.GPointer): ...

class ExternalMemoryProperties(GObject.GPointer): ...

class ExternalMemoryPropertiesKHR(GObject.GPointer): ...

class ExternalSemaphoreFeatureFlagBits(GObject.GPointer): ...

class ExternalSemaphoreFeatureFlagBitsKHR(GObject.GPointer): ...

class ExternalSemaphoreFeatureFlags(GObject.GPointer): ...

class ExternalSemaphoreFeatureFlagsKHR(GObject.GPointer): ...

class ExternalSemaphoreHandleTypeFlagBits(GObject.GPointer): ...

class ExternalSemaphoreHandleTypeFlagBitsKHR(GObject.GPointer): ...

class ExternalSemaphoreHandleTypeFlags(GObject.GPointer): ...

class ExternalSemaphoreHandleTypeFlagsKHR(GObject.GPointer): ...

class ExternalSemaphoreProperties(GObject.GPointer): ...

class ExternalSemaphorePropertiesKHR(GObject.GPointer): ...

class Fence(GObject.GPointer): ...

class FenceCreateFlagBits(GObject.GPointer): ...

class FenceCreateFlags(GObject.GPointer): ...

class FenceCreateInfo(GObject.GPointer): ...

class FenceGetFdInfoKHR(GObject.GPointer): ...

class FenceImportFlagBits(GObject.GPointer): ...

class FenceImportFlagBitsKHR(GObject.GPointer): ...

class FenceImportFlags(GObject.GPointer): ...

class FenceImportFlagsKHR(GObject.GPointer): ...

class Filter(GObject.GPointer): ...

class FilterCubicImageViewImageFormatPropertiesEXT(GObject.GPointer): ...

class Flags(GObject.GPointer): ...

class Format(GObject.GPointer): ...

class FormatFeatureFlagBits(GObject.GPointer): ...

class FormatFeatureFlags(GObject.GPointer): ...

class FormatProperties(GObject.GPointer): ...

class FormatProperties2(GObject.GPointer): ...

class FormatProperties2KHR(GObject.GPointer): ...

class Framebuffer(GObject.GPointer): ...

class FramebufferCreateFlags(GObject.GPointer): ...

class FramebufferCreateInfo(GObject.GPointer): ...

class FramebufferMixedSamplesCombinationNV(GObject.GPointer): ...

class FrontFace(GObject.GPointer): ...

class GeometryAABBNV(GObject.GPointer): ...

class GeometryDataNV(GObject.GPointer): ...

class GeometryFlagBitsNV(GObject.GPointer): ...

class GeometryFlagsNV(GObject.GPointer): ...

class GeometryInstanceFlagBitsNV(GObject.GPointer): ...

class GeometryInstanceFlagsNV(GObject.GPointer): ...

class GeometryNV(GObject.GPointer): ...

class GeometryTrianglesNV(GObject.GPointer): ...

class GeometryTypeNV(GObject.GPointer): ...

class GraphicsPipelineCreateInfo(GObject.GPointer): ...

class HdrMetadataEXT(GObject.GPointer): ...

class HeadlessSurfaceCreateFlagsEXT(GObject.GPointer): ...

class HeadlessSurfaceCreateInfoEXT(GObject.GPointer): ...

class Image(GObject.GPointer): ...

class ImageAspectFlagBits(GObject.GPointer): ...

class ImageAspectFlags(GObject.GPointer): ...

class ImageBlit(GObject.GPointer): ...

class ImageCopy(GObject.GPointer): ...

class ImageCreateFlagBits(GObject.GPointer): ...

class ImageCreateFlags(GObject.GPointer): ...

class ImageCreateInfo(GObject.GPointer): ...

class ImageDrmFormatModifierExplicitCreateInfoEXT(GObject.GPointer): ...

class ImageDrmFormatModifierListCreateInfoEXT(GObject.GPointer): ...

class ImageDrmFormatModifierPropertiesEXT(GObject.GPointer): ...

class ImageFormatListCreateInfoKHR(GObject.GPointer): ...

class ImageFormatProperties(GObject.GPointer): ...

class ImageFormatProperties2(GObject.GPointer): ...

class ImageFormatProperties2KHR(GObject.GPointer): ...

class ImageLayout(GObject.GPointer): ...

class ImageMemoryBarrier(GObject.GPointer): ...

class ImageMemoryRequirementsInfo2(GObject.GPointer): ...

class ImageMemoryRequirementsInfo2KHR(GObject.GPointer): ...

class ImagePlaneMemoryRequirementsInfo(GObject.GPointer): ...

class ImagePlaneMemoryRequirementsInfoKHR(GObject.GPointer): ...

class ImageResolve(GObject.GPointer): ...

class ImageSparseMemoryRequirementsInfo2(GObject.GPointer): ...

class ImageSparseMemoryRequirementsInfo2KHR(GObject.GPointer): ...

class ImageStencilUsageCreateInfoEXT(GObject.GPointer): ...

class ImageSubresource(GObject.GPointer): ...

class ImageSubresourceLayers(GObject.GPointer): ...

class ImageSubresourceRange(GObject.GPointer): ...

class ImageSwapchainCreateInfoKHR(GObject.GPointer): ...

class ImageTiling(GObject.GPointer): ...

class ImageType(GObject.GPointer): ...

class ImageUsageFlagBits(GObject.GPointer): ...

class ImageUsageFlags(GObject.GPointer): ...

class ImageView(GObject.GPointer): ...

class ImageViewASTCDecodeModeEXT(GObject.GPointer): ...

class ImageViewCreateFlagBits(GObject.GPointer): ...

class ImageViewCreateFlags(GObject.GPointer): ...

class ImageViewCreateInfo(GObject.GPointer): ...

class ImageViewHandleInfoNVX(GObject.GPointer): ...

class ImageViewType(GObject.GPointer): ...

class ImageViewUsageCreateInfo(GObject.GPointer): ...

class ImageViewUsageCreateInfoKHR(GObject.GPointer): ...

class ImportFenceFdInfoKHR(GObject.GPointer): ...

class ImportMemoryFdInfoKHR(GObject.GPointer): ...

class ImportMemoryHostPointerInfoEXT(GObject.GPointer): ...

class ImportSemaphoreFdInfoKHR(GObject.GPointer): ...

class IndexType(GObject.GPointer): ...

class IndirectCommandsLayoutCreateInfoNVX(GObject.GPointer): ...

class IndirectCommandsLayoutNVX(GObject.GPointer): ...

class IndirectCommandsLayoutTokenNVX(GObject.GPointer): ...

class IndirectCommandsLayoutUsageFlagBitsNVX(GObject.GPointer): ...

class IndirectCommandsLayoutUsageFlagsNVX(GObject.GPointer): ...

class IndirectCommandsTokenNVX(GObject.GPointer): ...

class IndirectCommandsTokenTypeNVX(GObject.GPointer): ...

class InputAttachmentAspectReference(GObject.GPointer): ...

class InputAttachmentAspectReferenceKHR(GObject.GPointer): ...

class Instance(GObject.GPointer): ...

class InstanceCreateFlags(GObject.GPointer): ...

class InstanceCreateInfo(GObject.GPointer): ...

class InternalAllocationType(GObject.GPointer): ...

class LayerProperties(GObject.GPointer): ...

class LogicOp(GObject.GPointer): ...

class MappedMemoryRange(GObject.GPointer): ...

class MemoryAllocateFlagBits(GObject.GPointer): ...

class MemoryAllocateFlagBitsKHR(GObject.GPointer): ...

class MemoryAllocateFlags(GObject.GPointer): ...

class MemoryAllocateFlagsInfo(GObject.GPointer): ...

class MemoryAllocateFlagsInfoKHR(GObject.GPointer): ...

class MemoryAllocateFlagsKHR(GObject.GPointer): ...

class MemoryAllocateInfo(GObject.GPointer): ...

class MemoryBarrier(GObject.GPointer): ...

class MemoryDedicatedAllocateInfo(GObject.GPointer): ...

class MemoryDedicatedAllocateInfoKHR(GObject.GPointer): ...

class MemoryDedicatedRequirements(GObject.GPointer): ...

class MemoryDedicatedRequirementsKHR(GObject.GPointer): ...

class MemoryFdPropertiesKHR(GObject.GPointer): ...

class MemoryGetFdInfoKHR(GObject.GPointer): ...

class MemoryHeap(GObject.GPointer): ...

class MemoryHeapFlagBits(GObject.GPointer): ...

class MemoryHeapFlags(GObject.GPointer): ...

class MemoryHostPointerPropertiesEXT(GObject.GPointer): ...

class MemoryMapFlags(GObject.GPointer): ...

class MemoryOverallocationBehaviorAMD(GObject.GPointer): ...

class MemoryPriorityAllocateInfoEXT(GObject.GPointer): ...

class MemoryPropertyFlagBits(GObject.GPointer): ...

class MemoryPropertyFlags(GObject.GPointer): ...

class MemoryRequirements(GObject.GPointer): ...

class MemoryRequirements2(GObject.GPointer): ...

class MemoryRequirements2KHR(GObject.GPointer): ...

class MemoryType(GObject.GPointer): ...

class MultisamplePropertiesEXT(GObject.GPointer): ...

class ObjectEntryTypeNVX(GObject.GPointer): ...

class ObjectEntryUsageFlagBitsNVX(GObject.GPointer): ...

class ObjectEntryUsageFlagsNVX(GObject.GPointer): ...

class ObjectTableCreateInfoNVX(GObject.GPointer): ...

class ObjectTableDescriptorSetEntryNVX(GObject.GPointer): ...

class ObjectTableEntryNVX(GObject.GPointer): ...

class ObjectTableIndexBufferEntryNVX(GObject.GPointer): ...

class ObjectTableNVX(GObject.GPointer): ...

class ObjectTablePipelineEntryNVX(GObject.GPointer): ...

class ObjectTablePushConstantEntryNVX(GObject.GPointer): ...

class ObjectTableVertexBufferEntryNVX(GObject.GPointer): ...

class ObjectType(GObject.GPointer): ...

class Offset2D(GObject.GPointer): ...

class Offset3D(GObject.GPointer): ...

class PastPresentationTimingGOOGLE(GObject.GPointer): ...

class PeerMemoryFeatureFlagBits(GObject.GPointer): ...

class PeerMemoryFeatureFlagBitsKHR(GObject.GPointer): ...

class PeerMemoryFeatureFlags(GObject.GPointer): ...

class PeerMemoryFeatureFlagsKHR(GObject.GPointer): ...

class PhysicalDevice(GObject.GPointer): ...

class PhysicalDevice16BitStorageFeatures(GObject.GPointer): ...

class PhysicalDevice16BitStorageFeaturesKHR(GObject.GPointer): ...

class PhysicalDevice8BitStorageFeaturesKHR(GObject.GPointer): ...

class PhysicalDeviceASTCDecodeFeaturesEXT(GObject.GPointer): ...

class PhysicalDeviceBlendOperationAdvancedFeaturesEXT(GObject.GPointer): ...

class PhysicalDeviceBlendOperationAdvancedPropertiesEXT(GObject.GPointer): ...

class PhysicalDeviceBufferAddressFeaturesEXT(GObject.GPointer): ...

class PhysicalDeviceBufferDeviceAddressFeaturesEXT(GObject.GPointer): ...

class PhysicalDeviceComputeShaderDerivativesFeaturesNV(GObject.GPointer): ...

class PhysicalDeviceConditionalRenderingFeaturesEXT(GObject.GPointer): ...

class PhysicalDeviceConservativeRasterizationPropertiesEXT(GObject.GPointer): ...

class PhysicalDeviceCooperativeMatrixFeaturesNV(GObject.GPointer): ...

class PhysicalDeviceCooperativeMatrixPropertiesNV(GObject.GPointer): ...

class PhysicalDeviceCornerSampledImageFeaturesNV(GObject.GPointer): ...

class PhysicalDeviceCoverageReductionModeFeaturesNV(GObject.GPointer): ...

class PhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV(GObject.GPointer): ...

class PhysicalDeviceDepthClipEnableFeaturesEXT(GObject.GPointer): ...

class PhysicalDeviceDepthStencilResolvePropertiesKHR(GObject.GPointer): ...

class PhysicalDeviceDescriptorIndexingFeaturesEXT(GObject.GPointer): ...

class PhysicalDeviceDescriptorIndexingPropertiesEXT(GObject.GPointer): ...

class PhysicalDeviceDiscardRectanglePropertiesEXT(GObject.GPointer): ...

class PhysicalDeviceDriverPropertiesKHR(GObject.GPointer): ...

class PhysicalDeviceExclusiveScissorFeaturesNV(GObject.GPointer): ...

class PhysicalDeviceExternalBufferInfo(GObject.GPointer): ...

class PhysicalDeviceExternalBufferInfoKHR(GObject.GPointer): ...

class PhysicalDeviceExternalFenceInfo(GObject.GPointer): ...

class PhysicalDeviceExternalFenceInfoKHR(GObject.GPointer): ...

class PhysicalDeviceExternalImageFormatInfo(GObject.GPointer): ...

class PhysicalDeviceExternalImageFormatInfoKHR(GObject.GPointer): ...

class PhysicalDeviceExternalMemoryHostPropertiesEXT(GObject.GPointer): ...

class PhysicalDeviceExternalSemaphoreInfo(GObject.GPointer): ...

class PhysicalDeviceExternalSemaphoreInfoKHR(GObject.GPointer): ...

class PhysicalDeviceFeatures(GObject.GPointer): ...

class PhysicalDeviceFeatures2(GObject.GPointer): ...

class PhysicalDeviceFeatures2KHR(GObject.GPointer): ...

class PhysicalDeviceFloat16Int8FeaturesKHR(GObject.GPointer): ...

class PhysicalDeviceFloatControlsPropertiesKHR(GObject.GPointer): ...

class PhysicalDeviceFragmentDensityMapFeaturesEXT(GObject.GPointer): ...

class PhysicalDeviceFragmentDensityMapPropertiesEXT(GObject.GPointer): ...

class PhysicalDeviceFragmentShaderBarycentricFeaturesNV(GObject.GPointer): ...

class PhysicalDeviceGroupProperties(GObject.GPointer): ...

class PhysicalDeviceGroupPropertiesKHR(GObject.GPointer): ...

class PhysicalDeviceHostQueryResetFeaturesEXT(GObject.GPointer): ...

class PhysicalDeviceIDProperties(GObject.GPointer): ...

class PhysicalDeviceIDPropertiesKHR(GObject.GPointer): ...

class PhysicalDeviceImageDrmFormatModifierInfoEXT(GObject.GPointer): ...

class PhysicalDeviceImageFormatInfo2(GObject.GPointer): ...

class PhysicalDeviceImageFormatInfo2KHR(GObject.GPointer): ...

class PhysicalDeviceImageViewImageFormatInfoEXT(GObject.GPointer): ...

class PhysicalDeviceInlineUniformBlockFeaturesEXT(GObject.GPointer): ...

class PhysicalDeviceInlineUniformBlockPropertiesEXT(GObject.GPointer): ...

class PhysicalDeviceLimits(GObject.GPointer): ...

class PhysicalDeviceMaintenance3Properties(GObject.GPointer): ...

class PhysicalDeviceMaintenance3PropertiesKHR(GObject.GPointer): ...

class PhysicalDeviceMemoryBudgetPropertiesEXT(GObject.GPointer): ...

class PhysicalDeviceMemoryPriorityFeaturesEXT(GObject.GPointer): ...

class PhysicalDeviceMemoryProperties(GObject.GPointer): ...

class PhysicalDeviceMemoryProperties2(GObject.GPointer): ...

class PhysicalDeviceMemoryProperties2KHR(GObject.GPointer): ...

class PhysicalDeviceMeshShaderFeaturesNV(GObject.GPointer): ...

class PhysicalDeviceMeshShaderPropertiesNV(GObject.GPointer): ...

class PhysicalDeviceMultiviewFeatures(GObject.GPointer): ...

class PhysicalDeviceMultiviewFeaturesKHR(GObject.GPointer): ...

class PhysicalDeviceMultiviewPerViewAttributesPropertiesNVX(GObject.GPointer): ...

class PhysicalDeviceMultiviewProperties(GObject.GPointer): ...

class PhysicalDeviceMultiviewPropertiesKHR(GObject.GPointer): ...

class PhysicalDevicePCIBusInfoPropertiesEXT(GObject.GPointer): ...

class PhysicalDevicePointClippingProperties(GObject.GPointer): ...

class PhysicalDevicePointClippingPropertiesKHR(GObject.GPointer): ...

class PhysicalDeviceProperties(GObject.GPointer): ...

class PhysicalDeviceProperties2(GObject.GPointer): ...

class PhysicalDeviceProperties2KHR(GObject.GPointer): ...

class PhysicalDeviceProtectedMemoryFeatures(GObject.GPointer): ...

class PhysicalDeviceProtectedMemoryProperties(GObject.GPointer): ...

class PhysicalDevicePushDescriptorPropertiesKHR(GObject.GPointer): ...

class PhysicalDeviceRayTracingPropertiesNV(GObject.GPointer): ...

class PhysicalDeviceRepresentativeFragmentTestFeaturesNV(GObject.GPointer): ...

class PhysicalDeviceSampleLocationsPropertiesEXT(GObject.GPointer): ...

class PhysicalDeviceSamplerFilterMinmaxPropertiesEXT(GObject.GPointer): ...

class PhysicalDeviceSamplerYcbcrConversionFeatures(GObject.GPointer): ...

class PhysicalDeviceSamplerYcbcrConversionFeaturesKHR(GObject.GPointer): ...

class PhysicalDeviceScalarBlockLayoutFeaturesEXT(GObject.GPointer): ...

class PhysicalDeviceShaderAtomicInt64FeaturesKHR(GObject.GPointer): ...

class PhysicalDeviceShaderCorePropertiesAMD(GObject.GPointer): ...

class PhysicalDeviceShaderDrawParameterFeatures(GObject.GPointer): ...

class PhysicalDeviceShaderDrawParametersFeatures(GObject.GPointer): ...

class PhysicalDeviceShaderImageFootprintFeaturesNV(GObject.GPointer): ...

class PhysicalDeviceShadingRateImageFeaturesNV(GObject.GPointer): ...

class PhysicalDeviceShadingRateImagePropertiesNV(GObject.GPointer): ...

class PhysicalDeviceSparseImageFormatInfo2(GObject.GPointer): ...

class PhysicalDeviceSparseImageFormatInfo2KHR(GObject.GPointer): ...

class PhysicalDeviceSparseProperties(GObject.GPointer): ...

class PhysicalDeviceSubgroupProperties(GObject.GPointer): ...

class PhysicalDeviceSurfaceInfo2KHR(GObject.GPointer): ...

class PhysicalDeviceTransformFeedbackFeaturesEXT(GObject.GPointer): ...

class PhysicalDeviceTransformFeedbackPropertiesEXT(GObject.GPointer): ...

class PhysicalDeviceType(GObject.GPointer): ...

class PhysicalDeviceUniformBufferStandardLayoutFeaturesKHR(GObject.GPointer): ...

class PhysicalDeviceVariablePointerFeatures(GObject.GPointer): ...

class PhysicalDeviceVariablePointerFeaturesKHR(GObject.GPointer): ...

class PhysicalDeviceVariablePointersFeatures(GObject.GPointer): ...

class PhysicalDeviceVariablePointersFeaturesKHR(GObject.GPointer): ...

class PhysicalDeviceVertexAttributeDivisorFeaturesEXT(GObject.GPointer): ...

class PhysicalDeviceVertexAttributeDivisorPropertiesEXT(GObject.GPointer): ...

class PhysicalDeviceVulkanMemoryModelFeaturesKHR(GObject.GPointer): ...

class PhysicalDeviceYcbcrImageArraysFeaturesEXT(GObject.GPointer): ...

class Pipeline(GObject.GPointer): ...

class PipelineBindPoint(GObject.GPointer): ...

class PipelineCache(GObject.GPointer): ...

class PipelineCacheCreateFlags(GObject.GPointer): ...

class PipelineCacheCreateInfo(GObject.GPointer): ...

class PipelineCacheHeaderVersion(GObject.GPointer): ...

class PipelineColorBlendAdvancedStateCreateInfoEXT(GObject.GPointer): ...

class PipelineColorBlendAttachmentState(GObject.GPointer): ...

class PipelineColorBlendStateCreateFlags(GObject.GPointer): ...

class PipelineColorBlendStateCreateInfo(GObject.GPointer): ...

class PipelineCoverageModulationStateCreateFlagsNV(GObject.GPointer): ...

class PipelineCoverageModulationStateCreateInfoNV(GObject.GPointer): ...

class PipelineCoverageReductionStateCreateFlagsNV(GObject.GPointer): ...

class PipelineCoverageReductionStateCreateInfoNV(GObject.GPointer): ...

class PipelineCoverageToColorStateCreateFlagsNV(GObject.GPointer): ...

class PipelineCoverageToColorStateCreateInfoNV(GObject.GPointer): ...

class PipelineCreateFlagBits(GObject.GPointer): ...

class PipelineCreateFlags(GObject.GPointer): ...

class PipelineCreationFeedbackCreateInfoEXT(GObject.GPointer): ...

class PipelineCreationFeedbackEXT(GObject.GPointer): ...

class PipelineCreationFeedbackFlagBitsEXT(GObject.GPointer): ...

class PipelineCreationFeedbackFlagsEXT(GObject.GPointer): ...

class PipelineDepthStencilStateCreateFlags(GObject.GPointer): ...

class PipelineDepthStencilStateCreateInfo(GObject.GPointer): ...

class PipelineDiscardRectangleStateCreateFlagsEXT(GObject.GPointer): ...

class PipelineDiscardRectangleStateCreateInfoEXT(GObject.GPointer): ...

class PipelineDynamicStateCreateFlags(GObject.GPointer): ...

class PipelineDynamicStateCreateInfo(GObject.GPointer): ...

class PipelineInputAssemblyStateCreateFlags(GObject.GPointer): ...

class PipelineInputAssemblyStateCreateInfo(GObject.GPointer): ...

class PipelineLayout(GObject.GPointer): ...

class PipelineLayoutCreateFlags(GObject.GPointer): ...

class PipelineLayoutCreateInfo(GObject.GPointer): ...

class PipelineMultisampleStateCreateFlags(GObject.GPointer): ...

class PipelineMultisampleStateCreateInfo(GObject.GPointer): ...

class PipelineRasterizationConservativeStateCreateFlagsEXT(GObject.GPointer): ...

class PipelineRasterizationConservativeStateCreateInfoEXT(GObject.GPointer): ...

class PipelineRasterizationDepthClipStateCreateFlagsEXT(GObject.GPointer): ...

class PipelineRasterizationDepthClipStateCreateInfoEXT(GObject.GPointer): ...

class PipelineRasterizationStateCreateFlags(GObject.GPointer): ...

class PipelineRasterizationStateCreateInfo(GObject.GPointer): ...

class PipelineRasterizationStateRasterizationOrderAMD(GObject.GPointer): ...

class PipelineRasterizationStateStreamCreateFlagsEXT(GObject.GPointer): ...

class PipelineRasterizationStateStreamCreateInfoEXT(GObject.GPointer): ...

class PipelineRepresentativeFragmentTestStateCreateInfoNV(GObject.GPointer): ...

class PipelineSampleLocationsStateCreateInfoEXT(GObject.GPointer): ...

class PipelineShaderStageCreateFlags(GObject.GPointer): ...

class PipelineShaderStageCreateInfo(GObject.GPointer): ...

class PipelineStageFlagBits(GObject.GPointer): ...

class PipelineStageFlags(GObject.GPointer): ...

class PipelineTessellationDomainOriginStateCreateInfo(GObject.GPointer): ...

class PipelineTessellationDomainOriginStateCreateInfoKHR(GObject.GPointer): ...

class PipelineTessellationStateCreateFlags(GObject.GPointer): ...

class PipelineTessellationStateCreateInfo(GObject.GPointer): ...

class PipelineVertexInputDivisorStateCreateInfoEXT(GObject.GPointer): ...

class PipelineVertexInputStateCreateFlags(GObject.GPointer): ...

class PipelineVertexInputStateCreateInfo(GObject.GPointer): ...

class PipelineViewportCoarseSampleOrderStateCreateInfoNV(GObject.GPointer): ...

class PipelineViewportExclusiveScissorStateCreateInfoNV(GObject.GPointer): ...

class PipelineViewportShadingRateImageStateCreateInfoNV(GObject.GPointer): ...

class PipelineViewportStateCreateFlags(GObject.GPointer): ...

class PipelineViewportStateCreateInfo(GObject.GPointer): ...

class PipelineViewportSwizzleStateCreateFlagsNV(GObject.GPointer): ...

class PipelineViewportSwizzleStateCreateInfoNV(GObject.GPointer): ...

class PipelineViewportWScalingStateCreateInfoNV(GObject.GPointer): ...

class PointClippingBehavior(GObject.GPointer): ...

class PointClippingBehaviorKHR(GObject.GPointer): ...

class PolygonMode(GObject.GPointer): ...

class PresentInfoKHR(GObject.GPointer): ...

class PresentModeKHR(GObject.GPointer): ...

class PresentRegionKHR(GObject.GPointer): ...

class PresentRegionsKHR(GObject.GPointer): ...

class PresentTimeGOOGLE(GObject.GPointer): ...

class PresentTimesInfoGOOGLE(GObject.GPointer): ...

class PrimitiveTopology(GObject.GPointer): ...

class ProtectedSubmitInfo(GObject.GPointer): ...

class PushConstantRange(GObject.GPointer): ...

class QueryControlFlagBits(GObject.GPointer): ...

class QueryControlFlags(GObject.GPointer): ...

class QueryPipelineStatisticFlagBits(GObject.GPointer): ...

class QueryPipelineStatisticFlags(GObject.GPointer): ...

class QueryPool(GObject.GPointer): ...

class QueryPoolCreateFlags(GObject.GPointer): ...

class QueryPoolCreateInfo(GObject.GPointer): ...

class QueryResultFlagBits(GObject.GPointer): ...

class QueryResultFlags(GObject.GPointer): ...

class QueryType(GObject.GPointer): ...

class Queue(GObject.GPointer): ...

class QueueFamilyCheckpointPropertiesNV(GObject.GPointer): ...

class QueueFamilyProperties(GObject.GPointer): ...

class QueueFamilyProperties2(GObject.GPointer): ...

class QueueFamilyProperties2KHR(GObject.GPointer): ...

class QueueFlagBits(GObject.GPointer): ...

class QueueFlags(GObject.GPointer): ...

class QueueGlobalPriorityEXT(GObject.GPointer): ...

class RasterizationOrderAMD(GObject.GPointer): ...

class RayTracingPipelineCreateInfoNV(GObject.GPointer): ...

class RayTracingShaderGroupCreateInfoNV(GObject.GPointer): ...

class RayTracingShaderGroupTypeNV(GObject.GPointer): ...

class Rect2D(GObject.GPointer): ...

class RectLayerKHR(GObject.GPointer): ...

class RefreshCycleDurationGOOGLE(GObject.GPointer): ...

class RenderPass(GObject.GPointer): ...

class RenderPassBeginInfo(GObject.GPointer): ...

class RenderPassCreateFlags(GObject.GPointer): ...

class RenderPassCreateInfo(GObject.GPointer): ...

class RenderPassCreateInfo2KHR(GObject.GPointer): ...

class RenderPassFragmentDensityMapCreateInfoEXT(GObject.GPointer): ...

class RenderPassInputAttachmentAspectCreateInfo(GObject.GPointer): ...

class RenderPassInputAttachmentAspectCreateInfoKHR(GObject.GPointer): ...

class RenderPassMultiviewCreateInfo(GObject.GPointer): ...

class RenderPassMultiviewCreateInfoKHR(GObject.GPointer): ...

class RenderPassSampleLocationsBeginInfoEXT(GObject.GPointer): ...

class ResolveModeFlagBitsKHR(GObject.GPointer): ...

class ResolveModeFlagsKHR(GObject.GPointer): ...

class Result(GObject.GPointer): ...

class SampleCountFlagBits(GObject.GPointer): ...

class SampleCountFlags(GObject.GPointer): ...

class SampleLocationEXT(GObject.GPointer): ...

class SampleLocationsInfoEXT(GObject.GPointer): ...

class SampleMask(GObject.GPointer): ...

class Sampler(GObject.GPointer): ...

class SamplerAddressMode(GObject.GPointer): ...

class SamplerCreateFlagBits(GObject.GPointer): ...

class SamplerCreateFlags(GObject.GPointer): ...

class SamplerCreateInfo(GObject.GPointer): ...

class SamplerMipmapMode(GObject.GPointer): ...

class SamplerReductionModeCreateInfoEXT(GObject.GPointer): ...

class SamplerReductionModeEXT(GObject.GPointer): ...

class SamplerYcbcrConversion(GObject.GPointer): ...

class SamplerYcbcrConversionCreateInfo(GObject.GPointer): ...

class SamplerYcbcrConversionCreateInfoKHR(GObject.GPointer): ...

class SamplerYcbcrConversionImageFormatProperties(GObject.GPointer): ...

class SamplerYcbcrConversionImageFormatPropertiesKHR(GObject.GPointer): ...

class SamplerYcbcrConversionInfo(GObject.GPointer): ...

class SamplerYcbcrConversionInfoKHR(GObject.GPointer): ...

class SamplerYcbcrConversionKHR(GObject.GPointer): ...

class SamplerYcbcrModelConversion(GObject.GPointer): ...

class SamplerYcbcrModelConversionKHR(GObject.GPointer): ...

class SamplerYcbcrRange(GObject.GPointer): ...

class SamplerYcbcrRangeKHR(GObject.GPointer): ...

class ScopeNV(GObject.GPointer): ...

class Semaphore(GObject.GPointer): ...

class SemaphoreCreateFlags(GObject.GPointer): ...

class SemaphoreCreateInfo(GObject.GPointer): ...

class SemaphoreGetFdInfoKHR(GObject.GPointer): ...

class SemaphoreImportFlagBits(GObject.GPointer): ...

class SemaphoreImportFlagBitsKHR(GObject.GPointer): ...

class SemaphoreImportFlags(GObject.GPointer): ...

class SemaphoreImportFlagsKHR(GObject.GPointer): ...

class ShaderInfoTypeAMD(GObject.GPointer): ...

class ShaderModule(GObject.GPointer): ...

class ShaderModuleCreateFlags(GObject.GPointer): ...

class ShaderModuleCreateInfo(GObject.GPointer): ...

class ShaderModuleValidationCacheCreateInfoEXT(GObject.GPointer): ...

class ShaderResourceUsageAMD(GObject.GPointer): ...

class ShaderStageFlagBits(GObject.GPointer): ...

class ShaderStageFlags(GObject.GPointer): ...

class ShaderStatisticsInfoAMD(GObject.GPointer): ...

class ShadingRatePaletteEntryNV(GObject.GPointer): ...

class ShadingRatePaletteNV(GObject.GPointer): ...

class SharedPresentSurfaceCapabilitiesKHR(GObject.GPointer): ...

class SharingMode(GObject.GPointer): ...

class SparseBufferMemoryBindInfo(GObject.GPointer): ...

class SparseImageFormatFlagBits(GObject.GPointer): ...

class SparseImageFormatFlags(GObject.GPointer): ...

class SparseImageFormatProperties(GObject.GPointer): ...

class SparseImageFormatProperties2(GObject.GPointer): ...

class SparseImageFormatProperties2KHR(GObject.GPointer): ...

class SparseImageMemoryBind(GObject.GPointer): ...

class SparseImageMemoryBindInfo(GObject.GPointer): ...

class SparseImageMemoryRequirements(GObject.GPointer): ...

class SparseImageMemoryRequirements2(GObject.GPointer): ...

class SparseImageMemoryRequirements2KHR(GObject.GPointer): ...

class SparseImageOpaqueMemoryBindInfo(GObject.GPointer): ...

class SparseMemoryBind(GObject.GPointer): ...

class SparseMemoryBindFlagBits(GObject.GPointer): ...

class SparseMemoryBindFlags(GObject.GPointer): ...

class SpecializationInfo(GObject.GPointer): ...

class SpecializationMapEntry(GObject.GPointer): ...

class StencilFaceFlagBits(GObject.GPointer): ...

class StencilFaceFlags(GObject.GPointer): ...

class StencilOp(GObject.GPointer): ...

class StencilOpState(GObject.GPointer): ...

class StructureType(GObject.GPointer): ...

class SubgroupFeatureFlagBits(GObject.GPointer): ...

class SubgroupFeatureFlags(GObject.GPointer): ...

class SubmitInfo(GObject.GPointer): ...

class SubpassBeginInfoKHR(GObject.GPointer): ...

class SubpassContents(GObject.GPointer): ...

class SubpassDependency(GObject.GPointer): ...

class SubpassDependency2KHR(GObject.GPointer): ...

class SubpassDescription(GObject.GPointer): ...

class SubpassDescription2KHR(GObject.GPointer): ...

class SubpassDescriptionDepthStencilResolveKHR(GObject.GPointer): ...

class SubpassDescriptionFlagBits(GObject.GPointer): ...

class SubpassDescriptionFlags(GObject.GPointer): ...

class SubpassEndInfoKHR(GObject.GPointer): ...

class SubpassSampleLocationsEXT(GObject.GPointer): ...

class SubresourceLayout(GObject.GPointer): ...

class SurfaceCapabilities2EXT(GObject.GPointer): ...

class SurfaceCapabilities2KHR(GObject.GPointer): ...

class SurfaceCapabilitiesKHR(GObject.GPointer): ...

class SurfaceCounterFlagBitsEXT(GObject.GPointer): ...

class SurfaceCounterFlagsEXT(GObject.GPointer): ...

class SurfaceFormat2KHR(GObject.GPointer): ...

class SurfaceFormatKHR(GObject.GPointer): ...

class SurfaceKHR(GObject.GPointer): ...

class SurfaceProtectedCapabilitiesKHR(GObject.GPointer): ...

class SurfaceTransformFlagBitsKHR(GObject.GPointer): ...

class SurfaceTransformFlagsKHR(GObject.GPointer): ...

class SwapchainCounterCreateInfoEXT(GObject.GPointer): ...

class SwapchainCreateFlagBitsKHR(GObject.GPointer): ...

class SwapchainCreateFlagsKHR(GObject.GPointer): ...

class SwapchainCreateInfoKHR(GObject.GPointer): ...

class SwapchainDisplayNativeHdrCreateInfoAMD(GObject.GPointer): ...

class SwapchainKHR(GObject.GPointer): ...

class SystemAllocationScope(GObject.GPointer): ...

class TessellationDomainOrigin(GObject.GPointer): ...

class TessellationDomainOriginKHR(GObject.GPointer): ...

class TextureLODGatherFormatPropertiesAMD(GObject.GPointer): ...

class TimeDomainEXT(GObject.GPointer): ...

class ValidationCacheCreateFlagsEXT(GObject.GPointer): ...

class ValidationCacheCreateInfoEXT(GObject.GPointer): ...

class ValidationCacheEXT(GObject.GPointer): ...

class ValidationCacheHeaderVersionEXT(GObject.GPointer): ...

class ValidationCheckEXT(GObject.GPointer): ...

class ValidationFeatureDisableEXT(GObject.GPointer): ...

class ValidationFeatureEnableEXT(GObject.GPointer): ...

class ValidationFeaturesEXT(GObject.GPointer): ...

class ValidationFlagsEXT(GObject.GPointer): ...

class VendorId(GObject.GPointer): ...

class VertexInputAttributeDescription(GObject.GPointer): ...

class VertexInputBindingDescription(GObject.GPointer): ...

class VertexInputBindingDivisorDescriptionEXT(GObject.GPointer): ...

class VertexInputRate(GObject.GPointer): ...

class Viewport(GObject.GPointer): ...

class ViewportCoordinateSwizzleNV(GObject.GPointer): ...

class ViewportSwizzleNV(GObject.GPointer): ...

class ViewportWScalingNV(GObject.GPointer): ...

class WriteDescriptorSet(GObject.GPointer): ...

class WriteDescriptorSetAccelerationStructureNV(GObject.GPointer): ...

class WriteDescriptorSetInlineUniformBlockEXT(GObject.GPointer): ...

class XYColorEXT(GObject.GPointer): ...

