import typing

from gi.repository import GObject
T = typing.TypeVar("T")

_namespace: str = "xlib"
_version: str = "2.0"

def open_display() -> None: ...

class Display(GObject.GPointer): ...

class Screen(GObject.GPointer): ...

class Visual(GObject.GPointer): ...

class XConfigureEvent(GObject.GPointer): ...

class XEvent(GObject.GPointer): ...

class XFontStruct(GObject.GPointer): ...

class XImage(GObject.GPointer): ...

class XTrapezoid(GObject.GPointer): ...

class XVisualInfo(GObject.GPointer): ...

class XWindowAttributes(GObject.GPointer): ...

