import typing

from gi.repository import GObject
T = typing.TypeVar("T")

_namespace: str = "xrandr"
_version: str = "1.3"

class CrtcChangeNotifyEvent(GObject.GPointer): ...

class NotifyEvent(GObject.GPointer): ...

class OutputChangeNotifyEvent(GObject.GPointer): ...

class OutputPropertyNotifyEvent(GObject.GPointer): ...

class ScreenChangeNotifyEvent(GObject.GPointer): ...

class ScreenResources(GObject.GPointer): ...

class ScreenSize(GObject.GPointer): ...

